### ISSUE TITLE
Python3 - pipeline_printout_graph

### ISSUE THREAD

**Issue by bunbun** [bunbun/ruffus#40]
louisplp says
Use the pipeline_printout_graph function on Python3 (any output format) causes the following error message
```pycon
    Traceback (most recent call last):
      ...
      File ".../pipeline/test_install/lib/python3.4/site-packages/ruffus/task.py", line 2975, in pipeline_printout_graph
        extra_data_for_signal = [t_verbose_logger(0, 0, None, runtime_data), job_history])
      File ".../pipeline/test_install/lib/python3.4/site-packages/ruffus/graph.py", line 1087, in graph_printout
        stream.write(result_str)
    TypeError: must be str, not bytes
```

Issue is resolve by opening the stream in binary mode (task.py, line 2952).
Also, if SVG is used, need to decode before replacing, and then recode in bytes (graph.py, line 1086). This is a quick fix and is not optimal...

**Comment by bunbun** [comment]
Reported by keren@eng.ucsd.edu, Jan 22, 2015
In Python 3, process.communicate() returns bytes, not strings. Calling stream.write(result_str) in ruffus.graph.graph_printout() causes an exception.

The solution is to open the output file with the 'b' flag.

I have tested this with pdf, svg, png, and jpg output, Python 3.3.1, and the current ruffus master branch

**Comment by bunbun** [comment]
keren@eng.ucsd.edu said on Jan 24, 2015
It seems like this string encoding problem occurs in other places too. For instance, in drmaa_wrapper.py, a tempfile is opened with mode 'w+b'. Calling write() with a string fails. Either call .encode() on the string first, or open the file with mode 'w' only.

**Comment by bunbun** [comment]
Thanks. It took me a while (not having migrated to python3 full time) to understand what this was about but I have applied your patch to the git repository. This will be in v. 2.7 hopefully in the next two weeks (before Valentine's day!)

Leo

**Comment by bunbun** [comment]
Passes new unittest
test/test_pipeline_printout_graph.py
